name: Power BI CI/CD

on:
  push:
    branches:
      - main  # Triggers on push to the main branch

jobs:
  power-bi:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code (optional if no code is needed)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Print "Hello, World!" in the job logs
      - name: Print Hello, World!
        run: echo "Hello, World!"

      # Step 3: Wait for 3 minutes
      - name: Wait for 2 minutes
        run: sleep 120  # Sleep for 120 seconds (2 minutes)

      # Step 4: Print message after the wait
      - name: Print message after wait
        run: echo "Pipeline waited for 2 minutes!"
